@startuml Co-Working Space Web App Use Case Diagram
left to right direction

rectangle "Co-Working Space Web App System" as System {
    usecase "Register" as UC1
    usecase "Login via\nemail and password" as UC2
    usecase "Logout" as UC3
    usecase "Book a Workspace\nlimited to a certain number\nper day" as UC4
    usecase "View Own Reservations" as UC5
    usecase "Edit Own Reservations" as UC6
    usecase "Cancel Own Reservations" as UC7
    usecase "View Available Workspaces" as UC8
    usecase "Edit User Profiles" as UC9
    usecase "View User Profiles" as UC10
    usecase "Administrate Workspaces\n(add, remove, edit)" as UC11
    usecase "Administrate Reservations\n(view all, modify, delete)" as UC12
    usecase "Administrate Users\n(view all, modify, delete)" as UC13
}

actor "User" as user
user -- UC1
user -- UC2
user -- UC3
user -- UC4
user -- UC5
user -- UC6
user -- UC7
user -- UC8
user -- UC9
user -- UC10

UC2 .> UC1 : include
UC3 .> UC2 : include

actor "Admin" as admin
UC1 -- admin 
UC2 -- admin 
UC11 -- admin 
UC12 -- admin 
UC13 -- admin 

@enduml


