@startuml Co-Working Space User Logout

title User Logout Process

participant "User" as user
participant "Server" as server

user -> server: GET /auth/logout

alt already authorized
    server -> user: response (logout success)
else not authorized
    server -> user: response (logout failed)
end

@enduml